import React from 'react'
import Head from 'next/head'
import { Box } from '@mui/material'
import Footer from './Footer'
import Navbar from './Navbar'

interface LayoutProps {
    children: React.ReactNode
}

const Layout = ({ children }: LayoutProps) => {
    return (
        <React.Fragment >
            <Head>
                <title>Own testlabs</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <Box component='main'>
                {children}
            </Box>
            <Footer />
        </React.Fragment>
    )
}

export default Layout